### ISSUE TITLE
Paper on arxiv ? 

### ISSUE THREAD

**Issue by ariel415el** [MiviaLab/DENet#1]
Hi,

How come your code is publicly available but the paper isn't ? 
The link you published here and the only one I could find on google is
 https://link.springer.com/article/10.1007/s00521-020-05572-5
and it seems to cost money to view??

Hope you'll upload your paper to arxiv as it seems very interesting.

**Comment by robertanto** [comment]
Unfortunately, once the paper has been published (and reviewed), it can not be uploaded on arxiv.
