### ISSUE TITLE
Update requirements to TensorFlow gpu 1.13.2

### ISSUE THREAD

**Issue by Ryojikn** [MiviaLab/DENet#3]
For anyone trying the presented model, be aware that you should first uninstall TensorFlow if you're using Colab.
And then install TensorFlow gpu 1.13.2 instead of tf 1.13.1

**Comment by robertanto** [comment]
Hi @Ryojikn , thank you for helping us!

Which problem have you encountered by using TensorFlow 1.13.1 (GPU)?
