### ISSUE TITLE
Training code 

### ISSUE THREAD

**Issue by ArthurZucker** [MiviaLab/DENet#4]
Thanks for this very interesting research! Thanks a lot !
 I was wondering if you could provide the full training code ? 
I am working on Audio Event Detection, and am really interesting in trying your architecture! 
Here is my email address : `arthur.zucker@etu.upmc.fr`

**Comment by robertanto** [comment]
Dear Arthur, 

the release of the training code is not in our plan at the moment. Nevertheless, don't hesitate to contact me at aroberto@unisa.it if you have any doubt.

Regards,
Antonio.
