### ISSUE TITLE
get_denet Error

### ISSUE THREAD

**Issue by WisamAbbasi** [MiviaLab/DENet#6]
I am getting the below error when importing get_denet, appreciate your help:

![Screenshot 2023-05-08 123744](https://user-images.githubusercontent.com/39978331/236803296-f980cfd2-72a5-4ea0-ab92-cb494362d0b9.png)

**Comment by robertanto** [comment]
Hi, thank you for opening an issue.

May you share your Python environment to understand if there are dependencies-related problems?
Have you tried to configure the `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` system variable as suggested by the error message?

**Comment by robertanto** [comment]
This issue was closed because it has been inactive.
